package bd2.project.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 18 14:41:02 EET 2014
// ---------------------------------------------------------------------
public interface BD2ProjectAppModule extends ApplicationModule {
    String doLoginDB(String userName, String password);
}
