package bd2.project.model.client;

import bd2.project.model.common.BD2ProjectAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 18 14:41:02 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BD2ProjectAppModuleClient extends ApplicationModuleImpl implements BD2ProjectAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BD2ProjectAppModuleClient() {
    }


    public String newFlightDB(String src_prm, String dest_prm,
                              String departHour_prm, String departDay_prm,
                              String duration_prm, String noSeats_prm,
                              String price_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"newFlightDB",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {src_prm, dest_prm, departHour_prm, departDay_prm, duration_prm, noSeats_prm, price_prm});
        return (String)_ret;
    }


    public String doLoginDB(String userName, String password) {
        Object _ret =
            this.riInvokeExportedMethod(this,"doLoginDB",new String [] {"java.lang.String","java.lang.String"},new Object[] {userName, password});
        return (String)_ret;
    }

    public String doReservationDB(String userName, String flightId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"doReservationDB",new String [] {"java.lang.String","java.lang.String"},new Object[] {userName, flightId});
        return (String)_ret;
    }

    public String createNewAccountDB(String cnp_prm, String firstname_prm,
                                     String lastname_prm, String address_prm,
                                     String phone_prm, String email_prm,
                                     String username_prm, String passwd_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createNewAccountDB",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {cnp_prm, firstname_prm, lastname_prm, address_prm, phone_prm, email_prm, username_prm, passwd_prm});
        return (String)_ret;
    }

    public String cancelFlightDB(String flightId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"cancelFlightDB",new String [] {"java.lang.String"},new Object[] {flightId});
        return (String)_ret;
    }

    public void doQueryResultReset() {
        Object _ret =
            this.riInvokeExportedMethod(this,"doQueryResultReset",null,null);
        return;
    }

    public String addPilotDB(String cnp_prm, String firstname_prm,
                             String lastname_prm, String address_prm,
                             String phone_prm, String sal_prm, String rank_prm,
                             String hiredate_prm, String comm_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"addPilotDB",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {cnp_prm, firstname_prm, lastname_prm, address_prm, phone_prm, sal_prm, rank_prm, hiredate_prm, comm_prm});
        return (String)_ret;
    }

    public String newPlaneDB(String airplane_name_prm,
                             String airplane_code_prm, String seats_prm,
                             String airplane_length_prm,
                             String airplane_height_prm,
                             String airplane_weight_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"newPlaneDB",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {airplane_name_prm, airplane_code_prm, seats_prm, airplane_length_prm, airplane_height_prm, airplane_weight_prm});
        return (String)_ret;
    }

    public String newFlightDB(String src_prm, String dest_prm,
                              String departHour_prm, String departDay_prm,
                              String duration_prm, String noSeats_prm,
                              String price_prm, String airplane_id_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"newFlightDB",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {src_prm, dest_prm, departHour_prm, departDay_prm, duration_prm, noSeats_prm, price_prm, airplane_id_prm});
        return (String)_ret;
    }

    public String cancelRservationDB(String reservation_id_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"cancelRservationDB",new String [] {"java.lang.String"},new Object[] {reservation_id_prm});
        return (String)_ret;
    }

    public String buyTicketDB(String reservation_id, String card_no,
                              String username_prm) {
        Object _ret =
            this.riInvokeExportedMethod(this,"buyTicketDB",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {reservation_id, card_no, username_prm});
        return (String)_ret;
    }
}
