package bd2.project.model.client;

import bd2.project.model.common.BD2ProjectAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 18 14:41:02 EET 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BD2ProjectAppModuleClient extends ApplicationModuleImpl implements BD2ProjectAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BD2ProjectAppModuleClient() {
    }


    public String doLoginDB(String userName, String password) {
        Object _ret =
            this.riInvokeExportedMethod(this,"doLoginDB",new String [] {"java.lang.String","java.lang.String"},new Object[] {userName, password});
        return (String)_ret;
    }

    public String doReservationDB(String clientId, String flightId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"doReservationDB",new String [] {"java.lang.String","java.lang.String"},new Object[] {clientId, flightId});
        return (String)_ret;
    }
}
